import json
from datetime import datetime

class RiskEngine:
    def __init__(self, config_path: str = "d:/VibeCode/Trade/trader/config/settings.json"):
        with open(config_path, 'r') as f:
            self.config = json.load(f).get("risk_limits", {})
        
    def risk_gate(self, signal: dict, account_state: dict, market_state: dict) -> dict:
        """
        Hard gatekeeper for survival. Cannot be bypassed.
        signal: Generated by strategy
        account_state: {equity, daily_pnl, consecutive_losses}
        market_state: {spread, is_news}
        Returns: {"allowed": bool, "reasons": list}
        """
        if not signal:
            return {"allowed": False, "reasons": ["No signal generated."]}
            
        reasons = []
        allowed = True
        
        # 1. Mandatory SL
        if signal.get('sl') is None or signal.get('sl') == 0:
            reasons.append("BLOCKED: Mandatory Stop Loss missing.")
            allowed = False
            
        # 2. Max consecutive losses today
        max_losses = self.config.get("max_consecutive_losses", 3)
        if account_state.get('consecutive_losses', 0) >= max_losses:
            reasons.append(f"BLOCKED: Reached daily max consecutive losses ({max_losses}).")
            allowed = False
            
        # 3. Daily loss cap
        max_loss_pct = self.config.get("max_daily_loss_percent", 6.0)
        daily_loss_pct = abs(account_state.get('daily_pnl', 0)) / (account_state.get('equity', 1000) + 1e-9) * 100
        if account_state.get('daily_pnl', 0) < 0 and daily_loss_pct >= max_loss_pct:
            reasons.append(f"BLOCKED: Max daily loss '{max_loss_pct}%' exceeded ({daily_loss_pct:.2f}%).")
            allowed = False
            
        # 4. Daily profit target hit (optional halt)
        target = self.config.get("daily_target_currency", float('inf'))
        if account_state.get('daily_pnl', 0) >= target:
            reasons.append(f"HALT: Daily target '{target}' reached. Preserving capital.")
            allowed = False
            
        # 5. Spread Check
        spreads = self.config.get("max_spread_points", {})
        sym_spread = spreads.get(signal.get('symbol', 'UNKNOWN'), 500)
        if market_state.get('spread', 0) > sym_spread:
            reasons.append(f"BLOCKED: Spread {market_state.get('spread')} > Max allowed {sym_spread}.")
            allowed = False
            
        # 6. News filter (stub)
        if market_state.get('is_news', False):
            reasons.append("BLOCKED: Trading inside 30-min high-impact news window.")
            allowed = False
            
        return {"allowed": allowed, "reasons": reasons}

risk_engine = RiskEngine()
