"""
Risk Gate V2 — Hard Gatekeeper + Spread/ATR Spike Cooldown
Cannot be bypassed. Capital preservation FIRST.
V2: Added 60-minute cooldown on spread spike or ATR deviation > 2.2x baseline.
     Daily target is now an ABSOLUTE HARD STOP — no "one more trade".
"""
import json
import logging
from datetime import datetime, timedelta, timezone

from backend.trader.config.paths import SETTINGS_PATH

logger = logging.getLogger("opus_logger")

# Load OPUS governor config for RR check
import json as _json_mod
with open(SETTINGS_PATH, encoding="utf-8") as _gf:
    _OPUS_CFG = _json_mod.load(_gf).get("opus_governor", {})

# Module-level cooldown tracker: {symbol: datetime_unlock}
_cooldown_until: dict = {}


class RiskEngine:
    def __init__(self, config_path=SETTINGS_PATH):
        with open(config_path, "r", encoding="utf-8") as f:
            payload = json.load(f)
        self.config = (payload or {}).get("risk_limits", {})
        self.strategy_config = (payload or {}).get("strategy", {})
        self.atr_cooldown_threshold = self.config.get("atr_deviation_cooldown_threshold", 2.2)
        self.cooldown_minutes = self.config.get("cooldown_minutes", 60)
        self.min_equity_by_symbol = self.config.get("min_equity_by_symbol", {}) or {}
        self.tick_volume_config = (self.strategy_config or {}).get("tick_volume_gate", {}) or {}
        # Backward compatibility for older config: keep XAU dedicated key if present.
        if "XAUUSD" not in self.min_equity_by_symbol:
            legacy_xau_min = float(self.config.get("xau_min_equity_threshold", 150.0) or 150.0)
            self.min_equity_by_symbol["XAUUSD"] = legacy_xau_min

    @staticmethod
    def _normalize_symbol_key(symbol: str) -> str:
        raw = str(symbol or "").upper().rstrip('MC.')
        if "XAU" in raw:
            return "XAUUSD"
        if "XAG" in raw:
            return "XAGUSD"
        if "BTC" in raw:
            return "BTCUSD"
        if "OIL" in raw:
            return "USOIL"
        if "30" in raw:
            return "US30"
        if "TEC" in raw or "NAS" in raw:
            return "USTEC"
        return raw

    def _get_symbol_min_equity(self, symbol: str) -> float:
        base_symbol = self._normalize_symbol_key(symbol)
        value = self.min_equity_by_symbol.get(base_symbol)
        if value is None:
            return 0.0
        try:
            return float(value)
        except Exception:
            return 0.0

    def _resolve_tick_volume_config(self, symbol: str) -> dict:
        base_cfg = dict(self.tick_volume_config or {})
        overrides = (base_cfg.get("symbol_overrides", {}) or {})
        raw_override = overrides.get(self._normalize_symbol_key(symbol))
        if isinstance(raw_override, dict):
            merged = dict(base_cfg)
            merged.update({k: v for k, v in raw_override.items() if v is not None})
            merged["symbol_overrides"] = overrides
            return merged
        return base_cfg

    @staticmethod
    def _execution_guard(signal: dict) -> dict:
        guard = signal.get("execution_guard", {})
        return dict(guard) if isinstance(guard, dict) else {}

    def risk_gate(self, signal: dict, account_state: dict, market_state: dict,
                  opus_status=None, current_session: str = "UNKNOWN",
                  session_consecutive_losses: int = None) -> dict:
        """
        Hard gatekeeper for survival. Cannot be bypassed.
        signal: Generated by strategy
        account_state: {equity, daily_pnl, consecutive_losses, margin_level, balance, margin_free, ...}
        market_state: {spread, is_news, atr_deviation}
        opus_status: OPUSStatus from governor (optional, for enhanced checks)
        session_consecutive_losses: Losses counted since bot session start (for --reset-pnl)
        Returns: {"allowed": bool, "reasons": list}
        """
        if not signal:
            return {"allowed": False, "reasons": ["No signal generated."]}

        reasons = []
        allowed = True
        backtest_mode = bool(market_state.get("backtest_mode", False))

        # 💰 [USER RULE] ด่าน 0: บันทึกค่าเงินก่อนเทรด (Capital Monitor)
        logger.info(
            f"  💰 CAPITAL: Bal=${account_state.get('balance', 0):.2f} "
            f"Eq=${account_state.get('equity', 0):.2f} "
            f"Free=${account_state.get('margin_free', 0):.2f}"
        )

        # 0.1: Minimum Equity Guard
        min_equity = self.config.get("min_equity_threshold", 50.0)
        if account_state.get('equity', 0) < min_equity:
            reasons.append(f"BLOCKED: Equity ${account_state.get('equity', 0):.2f} < Minimum ${min_equity:.2f}")
            allowed = False

        # 0.2: Global Margin Utilization Cap (Institutional Rule: 40% Max)
        # For a $150 account, total margin should not exceed $60 (40%)
        margin_used = account_state.get('margin', 0)
        equity = account_state.get('equity', 0)
        # Prevent division by zero, but use live equity
        safe_equity = max(equity, 1.0)
        margin_utilization = (margin_used / safe_equity) * 100
        if margin_utilization > 40.0:
            reasons.append(f"🛡️ [MARGIN CAP] Utilization {margin_utilization:.1f}% > 40% limit.")
            allowed = False

        # --- Session Check for Weekend ---
        symbol = signal.get('symbol', 'UNKNOWN')
        is_crypto = any(c in symbol.upper() for c in ["BTC", "ETH", "SOL", "BNB"])
        if current_session == "WEEKEND" and not is_crypto:
            reasons.append(f"BLOCKED: Weekend session - only crypto allowed for {symbol}")
            allowed = False

        # 👑 [INSTITUTIONAL] Strict XAU Limitation: Max 1 position
        if (not backtest_mode) and "XAU" in symbol.upper():
            # Check current open positions for XAU
            import MetaTrader5 as mt5
            positions = mt5.positions_get(symbol=symbol)
            pos_count = len(positions) if positions else 0
            if pos_count >= 1:
                reasons.append(f"🛡️ [STRICT] XAU Limit: Max 1 open position allowed (Current: {pos_count})")
                allowed = False

        # 👑 [INSTITUTIONAL] Per-symbol equity guard from settings.json
        # Example: risk_limits.min_equity_by_symbol.XAUUSD = 150
        per_symbol_min_equity = self._get_symbol_min_equity(symbol)
        if per_symbol_min_equity > 0 and account_state.get('equity', 0) < per_symbol_min_equity:
            reasons.append(
                f"🛡️ [LOCKED] {self._normalize_symbol_key(symbol)} requires "
                f"${per_symbol_min_equity:.0f} equity (Current: ${account_state.get('equity', 0):.2f})."
            )
            allowed = False

        # ═══ OPUS GOVERNOR CHECKS (supersede all) ═══
        if opus_status is not None:
            if not opus_status.trade_allowed:
                # ─── SURVIVOR MODE BYPASS ───
                # If the block is purely due to Floating DD, allow XAU or BTC with restricted lot
                is_recovery_asset = any(a in symbol.upper() for a in ["XAU", "BTC"])
                if is_recovery_asset and "FLOATING DD CRITICAL" in opus_status.block_reason:
                    logger.info(f"🛡️ [SURVIVOR MODE] Bypassing DD block for {symbol} (Recovery Trade)")
                else:
                    reasons.append(f"GOVERNOR: {opus_status.block_reason}")
                    allowed = False
            
            if opus_status.defensive_mode and allowed:
                # Block counter-trend strategies in defensive mode
                model = signal.get('model', '').lower()
                if 'counter' in model or 'breakout' in model:
                    reasons.append(f"DEFENSIVE MODE: {model} blocked ({opus_status.defensive_reasons})")
                    allowed = False

        # 1. Mandatory SL
        if signal.get('sl') is None or signal.get('sl') == 0:
            reasons.append("BLOCKED: Mandatory Stop Loss missing.")
            allowed = False

        # 2. Max consecutive losses today
        max_losses = self.config.get("max_consecutive_losses", 3)
        current_losses = session_consecutive_losses if session_consecutive_losses is not None else account_state.get('consecutive_losses', 0)
        if current_losses >= max_losses:
            reasons.append(f"BLOCKED: Reached daily max consecutive losses ({max_losses}).")
            allowed = False

        # 3. Daily loss cap
        max_loss_pct = self.config.get("max_daily_loss_percent", 6.0)
        daily_loss_pct = abs(account_state.get('daily_pnl', 0)) / (account_state.get('equity', 1000) + 1e-9) * 100
        if account_state.get('daily_pnl', 0) < 0 and daily_loss_pct >= max_loss_pct:
            reasons.append(f"BLOCKED: Max daily loss '{max_loss_pct}%' exceeded ({daily_loss_pct:.2f}%).")
            allowed = False

        # 4. Daily profit target HARD STOP (absolute — no "one more trade")
        target = self.config.get("daily_target_currency", float('inf'))
        daily_pnl = account_state.get('daily_pnl', 0)
        if daily_pnl >= target:
            reasons.append(
                f"[STOP] Daily target ${target:.2f} reached "
                f"(PnL=${daily_pnl:.2f}). NO MORE TRADES TODAY."
            )
            allowed = False

        # 5. Spread Check
        spreads = self.config.get("max_spread_points", {})
        symbol = signal.get('symbol', 'UNKNOWN')
        
        # Normalize broker symbol variants (XAUUSDm → XAUUSD, USOILm → USOIL)
        base_symbol = symbol.rstrip('mcMC.').upper()
        if "XAU" in base_symbol: base_symbol = "XAUUSD"
        if "XAG" in base_symbol: base_symbol = "XAGUSD"
        if "BTC" in base_symbol: base_symbol = "BTCUSD"
        if "OIL" in base_symbol: base_symbol = "USOIL"
        if "30" in base_symbol: base_symbol = "US30"
        if "TEC" in base_symbol or "NAS" in base_symbol: base_symbol = "USTEC"
        
        sym_spread = spreads.get(base_symbol, spreads.get(symbol, 1000))
        
        # --- Monday Open Spread Protection (Enhanced V2) ---
        now_th = datetime.now(timezone.utc) + timedelta(hours=7) # Local TH time
        is_monday_morning = now_th.weekday() == 0 and 4 <= now_th.hour < 8
        effective_max_spread = sym_spread
        
        if (not backtest_mode) and is_monday_morning:
            effective_max_spread = sym_spread * 0.8
            logger.info(f"🛡️ Monday Open Guard: Using tighter spread limit {effective_max_spread} for {symbol}")

        current_spread = market_state.get('spread', 0)
        execution_guard = self._execution_guard(signal)
        spread_override = float(execution_guard.get("max_spread_points", 0.0) or 0.0)
        if spread_override > 0:
            effective_max_spread = min(float(effective_max_spread), spread_override)
        if current_spread > effective_max_spread:
            reasons.append(f"BLOCKED: Spread {current_spread} > Max allowed {effective_max_spread} for {symbol} ({base_symbol}).")
            allowed = False
            self._trigger_cooldown(symbol, f"Spread spike {current_spread} > {effective_max_spread}")

        # 👑 [USER RULE] XAU Advisory for Monday
        if (not backtest_mode) and is_monday_morning and "XAU" in symbol.upper():
            logger.info(f"⚠️ High Sensitivity: XAU position monitoring active for Monday Open.")

        # 6. News filter (Institutional + Manual Override)
        news_model = str(signal.get("model", "")).upper()
        news_trade_window = bool(market_state.get("news_trade_window", False))
        if not backtest_mode:
            from backend.trader.services.news_filter import news_filter

            live_news_block = market_state.get("is_news", False) or (not news_filter.is_safe(symbol))
            if news_model == "NEWS_SESSION_MOMENTUM":
                if not news_trade_window:
                    reasons.append("BLOCKED: NEWS_SESSION_MOMENTUM requires an active news trade window.")
                    allowed = False
            elif live_news_block:
                reasons.append("BLOCKED: Trading inside ±30-min HIGH-impact news window.")
                allowed = False

        # 6.5 Market Volume Filter (Tiered)
        min_vol_ratio = self.config.get("min_volume_ratio", 0.8)
        min_vol_ratio_hard = self.config.get("min_volume_ratio_hard", 0.4)
        current_vol_ratio = market_state.get("vol_ratio", 1.0)
        
        vol_warning = False
        if current_vol_ratio < min_vol_ratio_hard:
            reasons.append(f"BLOCKED: Dead Market (Vol Ratio {current_vol_ratio:.2f} < {min_vol_ratio_hard})")
            allowed = False
        elif current_vol_ratio < min_vol_ratio:
            vol_warning = True
            reasons.append(f"ADVISORY: Low Volatility (Vol Ratio {current_vol_ratio:.2f}) - Reduced Lot Mode")

        # 6.6 Tick Volume Entry Gate (institutional participation)
        tv_cfg = self._resolve_tick_volume_config(signal.get("symbol", ""))
        has_tick_volume_ctx = any(
            key in market_state for key in ("tick_vol_ratio", "tick_volume_side", "tick_volume_climax")
        )
        if bool(tv_cfg.get("enabled", False)) and has_tick_volume_ctx:
            model = str(signal.get("model", "")).upper()
            side = str(signal.get("side", "")).upper()
            strict_models = [str(m).upper() for m in tv_cfg.get("strict_entry_models", []) if str(m).strip()]
            allow_low_volume_models = {
                str(m).upper() for m in tv_cfg.get("allow_low_volume_models", []) if str(m).strip()
            }
            strict_entry = (model in strict_models) if strict_models else (model not in allow_low_volume_models)

            tv_ratio = market_state.get("tick_vol_ratio", current_vol_ratio)
            try:
                tv_ratio = float(tv_ratio)
            except Exception:
                tv_ratio = current_vol_ratio

            entry_ratio_min = float(tv_cfg.get("entry_ratio_min", 1.15))
            large_volume_ratio_min = max(
                entry_ratio_min,
                float(tv_cfg.get("large_volume_ratio_min", 1.35))
            )
            require_large_volume = bool(tv_cfg.get("require_large_volume_for_strict_models", True))
            if strict_entry and tv_ratio < entry_ratio_min:
                reasons.append(
                    f"BLOCKED: Tick Volume {tv_ratio:.2f}x below entry gate "
                    f"{entry_ratio_min:.2f}x"
                )
                allowed = False

            if strict_entry and require_large_volume and tv_ratio < large_volume_ratio_min:
                reasons.append(
                    f"BLOCKED: Tick Volume {tv_ratio:.2f}x below large-volume gate "
                    f"{large_volume_ratio_min:.2f}x"
                )
                allowed = False

            if bool(market_state.get("tick_volume_climax", False)):
                reasons.append(f"BLOCKED: Tick Volume climax/exhaustion ({tv_ratio:.2f}x)")
                allowed = False

            volume_side = str(market_state.get("tick_volume_side", "NEUTRAL")).upper()
            if (
                strict_entry
                and bool(tv_cfg.get("block_neutral_large_volume", True))
                and volume_side == "NEUTRAL"
                and tv_ratio >= large_volume_ratio_min
            ):
                reasons.append(
                    f"BLOCKED: Large Tick Volume {tv_ratio:.2f}x but no directional pressure"
                )
                allowed = False

            opposite_block_ratio = float(tv_cfg.get("opposite_block_ratio", 1.35))
            if side in {"BUY", "SELL"} and volume_side in {"BUY", "SELL"} and volume_side != side and tv_ratio >= opposite_block_ratio:
                reasons.append(
                    f"BLOCKED: Tick Volume pressure {volume_side} opposes {side} "
                    f"({tv_ratio:.2f}x)"
                )
                allowed = False

        # 7. ATR Deviation Cooldown (V2)
        cooldown_ok, cooldown_reason = self._check_volatility_cooldown(signal, market_state)
        if not cooldown_ok:
            reasons.append(cooldown_reason)
            allowed = False

        # 8. RR Minimum Check
        if opus_status is not None and signal.get('sl') and signal.get('tp1'):
            entry = signal.get('entry_price', 0)
            sl = signal.get('sl', 0)
            tp = signal.get('tp1', 0)
            risk = abs(entry - sl)
            reward = abs(tp - entry)
            if risk > 0:
                rr = reward / risk
                rr_min = _OPUS_CFG.get("rr_minimum", 1.2)
                # V2 Optimization: Allow 1.0R if confidence is exceptionally high (>= 75%)
                if signal.get('confidence', 0) >= 0.75:
                    rr_min = 1.0
                
                if rr < rr_min:
                    reasons.append(f"BLOCKED: RR {rr:.2f} < minimum {rr_min}")
                    allowed = False

        # 9. Correlation Hedge / Exposure Limit (V2)
        # REMOVED: User explicitly requested to allow trading both BUY and SELL without limits between XAU/XAG.

        return {"allowed": allowed, "reasons": reasons}

    def _check_volatility_cooldown(self, signal: dict, market_state: dict) -> tuple:
        """
        Check and enforce 60-minute cooldown after:
        - ATR deviation > 2.2x baseline
        - Spread spike above limit (already triggers in spread check)
        """
        global _cooldown_until
        symbol = signal.get('symbol', 'UNKNOWN')
        now = datetime.now(timezone.utc)

        # Check existing cooldown
        if symbol in _cooldown_until and now < _cooldown_until[symbol]:
            remaining = int((_cooldown_until[symbol] - now).total_seconds() // 60)
            return False, f"[COOLDOWN] {remaining}m remaining after volatility/spread spike"

        # ATR deviation check
        atr_deviation = market_state.get('atr_deviation', 1.0)
        if atr_deviation > self.atr_cooldown_threshold:
            self._trigger_cooldown(
                symbol,
                f"ATR deviation {atr_deviation:.2f}x > {self.atr_cooldown_threshold}x threshold"
            )
            return False, (
                f"[COOLDOWN] ATR deviation {atr_deviation:.2f}x > "
                f"{self.atr_cooldown_threshold}x - no trades for {self.cooldown_minutes}m"
            )

        return True, ""

    def trigger_cooldown(self, symbol: str, reason: str):
        """Public method to trigger a cooldown for a symbol."""
        self._trigger_cooldown(symbol, reason)

    def _trigger_cooldown(self, symbol: str, reason: str):
        """Set a cooldown lock for the given symbol."""
        global _cooldown_until
        unlock_at = datetime.now(timezone.utc) + timedelta(minutes=self.cooldown_minutes)
        _cooldown_until[symbol] = unlock_at
        logger.warning(
            f"🔒 COOLDOWN SET: {symbol} locked until {unlock_at.strftime('%H:%M:%S')} UTC — {reason}"
        )


# Singleton instance
risk_engine = RiskEngine()
